CREATE DATABASE LD1
GO
USE LD1
GO
CREATE TABLE SanPham(
	MaSP INT IDENTITY(1,1) NOT NULL,
	TenSP NVARCHAR(50),
	LoaiSP NVARCHAR(50),
	GiaTien MONEY
);
GO

CREATE TABLE HoaDon(
	SoHD INT IDENTITY(1,1) NOT NULL,
	NGAYDH DATE,
	NGAYGH DATE
);
GO

CREATE TABLE CTHD(
	SoHD INT,
	MaSP INT,
	SoLuong INT,
	DonGia MONEY
);
GO

ALTER TABLE SanPham ADD CONSTRAINT PK_SanPham PRIMARY KEY (MaSP);
ALTER TABLE HoaDon ADD CONSTRAINT PK_HoaDon PRIMARY KEY (SoHD);
ALTER TABLE CTHD ADD CONSTRAINT PK_CTHD PRIMARY KEY (MaSP,SoHD);

ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP);
ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD_HoaDon FOREIGN KEY (SoHD) REFERENCES HoaDon(SoHD);

--Cau 2
CREATE PROCEDURE InsertSanPham
	@TenSP NVARCHAR(50),
	@LoaiSP NVARCHAR(50),
	@GiaTien MONEY
AS
BEGIN
	INSERT INTO SanPham VALUES (@TenSP,@LoaiSP,@GiaTien)
	PRINT 'Insert thanh cong'
END

CREATE PROCEDURE InsertHoaDon
	@NGAYDH DATE,
	@NGAYGH DATE
AS
BEGIN
	INSERT INTO HoaDon VALUES (@NGAYDH,@NGAYGH)
	PRINT 'Insert thanh cong'
END

CREATE PROCEDURE InsertCTHD
	@SoHD INT,
	@MaSP INT,
	@SoLuong INT,
	@DonGia MONEY
AS
BEGIN
	IF @SoHD IS NULL OR @MaSP IS NULL
		PRINT 'Cac thong tin ten khong duoc null'
	ELSE
		INSERT INTO CTHD VALUES (@SoHD,@MaSP,@SoLuong,@DonGia)
		PRINT ' Insert thanh cong'
END

--Cau 3
CREATE FUNCTION Cau3 (@TenSP NVARCHAR(50),
	@LoaiSP NVARCHAR(50),
	@GiaTien MONEY)
RETURNS TABLE
AS
RETURN ( SELECT MaSP FROM SanPham WHERE TenSP = @TenSP AND LoaiSP = @LoaiSP AND GiaTien = @GiaTien)
--Cau 4 Tạo View lưu thông tin của TOP 5 có giá trị đơn hàng lớn nhất, gồm các thông tin sau:
--MaSP, TenSP, LoaiSP, NgayDH, NgayGH, SoLuong, DonGia, “Gia Tri Max”.
CREATE VIEW Cau4
AS
SELECT TOP 5 SanPham.MaSP, TenSP, LoaiSP, NgayDH, NgayGH, SoLuong, DonGia, SoLuong*DonGia AS ThanhTien FROM SanPham JOIN CTHD ON SanPham.MaSP = CTHD.MaSP
JOIN HoaDon ON CTHD.SoHD = HoaDon.SoHD
GROUP BY SanPham.MaSP, TenSP, LoaiSP, NgayDH, NgayGH, SoLuong, DonGia
ORDER BY ThanhTien DESC
--Cau 5
CREATE PROCEDURE Cau5
	@SoLuong INT
AS
BEGIN
	BEGIN TRY
	BEGIN TRANSACTION
	IF @SoLuong IS NULL
		PRINT N'So luong khong duoc de trong'
	ELSE
		DECLARE @BangHD TABLE (SoHD INT)
		DECLARE @BangSP TABLE (MaSP INT)
		INSERT INTO @BangHD SELECT SoHD FROM CTHD WHERE SoLuong = @SoLuong
		INSERT INTO @BangSP SELECT MaSP FROM CTHD WHERE SoLuong = @SoLuong
		DELETE FROM CTHD WHERE SoLuong = @SoLuong
		DELETE FROM HoaDon WHERE SoHD IN (SELECT SoHD FROM @BangHD)
		DELETE FROM SanPham WHERE MaSP IN (SELECT MaSP FROM @BangSP)
	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
	PRINT 'Loi xoa'
	ROLLBACK TRANSACTION
	END CATCH
END

