CREATE DATABASE [COM2034-IT17317]
GO
USE [COM2034-IT17317]
GO

CREATE TABLE RULER(
	ID VARCHAR(10) PRIMARY KEY,
	[NAME] NVARCHAR(50) NOT NULL,
	[DESCRIPTION] NVARCHAR(MAX),
	[LENGTH] INT NOT NULL,
	UNIT VARCHAR(10) NOT NULL,
	PRICE MONEY NOT NULL
)
GO
INSERT INTO RULER(ID, [NAME], [DESCRIPTION], [LENGTH], UNIT, PRICE)
VALUES('R001',N'THƯỚC KẺ THIÊN LONG', NULL,30,'CM',10000)
INSERT INTO RULER
VALUES('R002',N'THƯỚC KẺ THIÊN LONG', NULL,30,'CM',10000)
INSERT INTO RULER(ID, [NAME], [LENGTH], UNIT, PRICE)
VALUES('R003',N'THƯỚC KẺ THIÊN LONG',30,'CM',10000)
UPDATE RULER SET [NAME] = N'THƯỚC KẺ HỒNG HÀ', PRICE = 9000
WHERE ID = 'R002'
UPDATE RULER SET [NAME] = N'THƯỚC THIÊN LONG VIP', [LENGTH] = 60
WHERE ID = 'R003'
DELETE FROM RULER
WHERE [NAME] LIKE N'%THIÊN LONG%'
SELECT * FROM RULER
