CREATE DATABASE [SU22_COM203_IT17317]
GO
USE [SU22_COM203_IT17317]
GO

CREATE TABLE RULER(
	RULERID INT IDENTITY(1,1) NOT NULL,
	RULERNAME NVARCHAR(50) NOT NULL,
	[DESCRIPTION] NVARCHAR(MAX),
	QUANTITY INT NOT NULL,
	CURRENTPRICE MONEY NOT NULL,
	MATERIAL NVARCHAR(50),
	[LENGTH] INT,
	UNIT VARCHAR(5),
	MADANHMUC INT
);
GO
CREATE TABLE KHACHHANG(
	MAKHACHHANG INT IDENTITY(1,1) NOT NULL,
	MATKHAU VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	DIACHI NVARCHAR(MAX),
	GIOITINH BIT,
	NGAYSINH DATE
);
GO
CREATE TABLE DANHMUC(
	MADANHMUC INT IDENTITY(1,1) NOT NULL,
	TENDANHMUC NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE HOADON(
	MAHOADON INT IDENTITY(1,1) NOT NULL,
	NGAYTAO DATE NOT NULL,
	MAKHACHHANG INT NOT NULL
);
GO
CREATE TABLE HOADONCHITIET(
	MAHOADON INT NOT NULL,
	RULERID INT NOT NULL,
	SOLUONGMUA INT NOT NULL,
	DONGIA MONEY NOT NULL,
);
GO

-- KHOA CHINH
ALTER TABLE RULER ADD CONSTRAINT PRI_RULER PRIMARY KEY (RULERID);
ALTER TABLE KHACHHANG ADD CONSTRAINT PRI_KHACHANG PRIMARY KEY (MAKHACHHANG);
ALTER TABLE DANHMUC ADD CONSTRAINT PRI_DANHMUC PRIMARY KEY (MADANHMUC);
ALTER TABLE HOADON ADD CONSTRAINT PRI_HOADON PRIMARY KEY (MAHOADON);
ALTER TABLE HOADONCHITIET ADD CONSTRAINT PRI_HOADONCHOTIET PRIMARY KEY (MAHOADON, RULERID);
-- KHOA NGOAI
ALTER TABLE RULER ADD CONSTRAINT FK_RULER_DANHMUC FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE HOADONCHITIET ADD CONSTRAINT FK_HOADONCHITIET_RULER FOREIGN KEY (RULERID) REFERENCES RULER(RULERID);
ALTER TABLE HOADONCHITIET ADD CONSTRAINT FK_HOADONCHITIET_HOADON FOREIGN KEY (MAHOADON) REFERENCES HOADON(MAHOADON);

INSERT INTO KHACHHANG VALUES (N'ABCDEF',N'NGUYEN VAN A',N'NGUYENVANA@GMAIL.COM',N'HANOI',0,'1989/07/12'),
							 (N'ABCDEF',N'NGUYEN VAN B',N'NGUYENVANB@GMAIL.COM',N'HANOI',0,'1990/03/24');
INSERT INTO DANHMUC VALUES (N'IT'),
						   (N'UDPM');
INSERT INTO RULER VALUES (N'THIEN LONG',NULL,3,10000,N'NHUA',30,N'CM',1),
						 (N'HONG HA',NULL,5,9000,N'GO',90,N'CM',2);
INSERT INTO HOADON VALUES ('2022/05/12',1),
						  ('2022/05/13',2);
INSERT INTO HOADONCHITIET VALUES (1,1,4,9000),
								 (2,2,4,10000);
SELECT * FROM RULER
SELECT * FROM KHACHHANG
SELECT * FROM DANHMUC
SELECT * FROM HOADON
SELECT * FROM HOADONCHITIET